#!/bin/bash
# VideoTranslator Studio — installer (one-line install)
#
# Usage:
#   bash <(curl -sL https://raw.githubusercontent.com/Vojtech-Pet/videotranslator-studio/main/install.sh)
#
# Override:
#   VTS_DIR=$HOME/apps/vts bash install.sh    # custom install dir
#   VTS_PY_VERSION=3.11 bash install.sh       # custom python version
set -e

VTS_DIR="${VTS_DIR:-$HOME/.local/share/videotranslator-studio}"
VTS_PY_VERSION="${VTS_PY_VERSION:-3.10}"
VTS_ENV_NAME="${VTS_ENV_NAME:-videotranslator}"
MINIFORGE_DIR="${MINIFORGE_DIR:-$HOME/miniforge3}"
REPO_URL="https://github.com/Vojtech-Pet/videotranslator-studio.git"

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[install]${NC} $*"; }
warn()  { echo -e "${YELLOW}[install]${NC} $*" >&2; }
err()   { echo -e "${RED}[install]${NC} $*" >&2; }

# ── 1. Sanity checks ──────────────────────────────────────────────────────────
[[ "$(uname -s)" == "Linux" ]] || { err "Linux only. Vidím: $(uname -s)"; exit 1; }
command -v git    >/dev/null || { err "Git nie je nainštalovaný. sudo apt install git"; exit 1; }
command -v ffmpeg >/dev/null || warn "ffmpeg nie je v PATH — odporúčam: sudo apt install ffmpeg"

# ── 2. Miniforge3 ─────────────────────────────────────────────────────────────
if [[ ! -x "$MINIFORGE_DIR/bin/conda" ]]; then
    info "Inštalujem Miniforge3 do $MINIFORGE_DIR"
    INSTALLER="/tmp/miniforge3-installer.sh"
    curl -fsSL "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh" -o "$INSTALLER"
    bash "$INSTALLER" -b -p "$MINIFORGE_DIR"
    rm -f "$INSTALLER"
fi
source "$MINIFORGE_DIR/etc/profile.d/conda.sh"

# ── 3. Conda env ──────────────────────────────────────────────────────────────
if conda env list | grep -q "^$VTS_ENV_NAME "; then
    info "Env '$VTS_ENV_NAME' už existuje, preskakujem create"
else
    info "Vytvaram conda env '$VTS_ENV_NAME' (Python $VTS_PY_VERSION)"
    conda create -y -n "$VTS_ENV_NAME" "python=$VTS_PY_VERSION" pip
fi
conda activate "$VTS_ENV_NAME"

# ── 4. Repo ───────────────────────────────────────────────────────────────────
if [[ -d "$VTS_DIR/.git" ]]; then
    info "Aktualizujem repo v $VTS_DIR"
    git -C "$VTS_DIR" pull --ff-only
else
    info "Klonujem repo do $VTS_DIR"
    mkdir -p "$(dirname "$VTS_DIR")"
    git clone "$REPO_URL" "$VTS_DIR"
fi

# ── 5. Python deps ────────────────────────────────────────────────────────────
info "Inštalujem Python dependencies (5-15 min)"
pip install --upgrade pip wheel
pip install -r "$VTS_DIR/requirements.txt"

# ── 6. CUDA libs (optional, for GPU acceleration) ─────────────────────────────
if command -v nvidia-smi >/dev/null 2>&1; then
    info "GPU detekované, inštalujem CUDA dependencies"
    pip install nvidia-cuda-runtime-cu12 nvidia-cublas-cu12 nvidia-cusparse-cu12 \
                nvidia-cuda-nvrtc-cu12 nvidia-nvjitlink-cu12 || \
        warn "CUDA libs install zlyhal — pôjdeš na CPU"
else
    warn "Žiadne NVIDIA GPU — VTS bude bežať na CPU (pomalšie)"
fi

# ── 7. Desktop shortcut ───────────────────────────────────────────────────────
DESKTOP_FILE="$HOME/.local/share/applications/videotranslator-studio.desktop"
mkdir -p "$(dirname "$DESKTOP_FILE")"
cat > "$DESKTOP_FILE" <<EOF
[Desktop Entry]
Version=1.0
Type=Application
Name=VideoTranslator Studio
Comment=EN→SK video dubbing pipeline
Exec=$VTS_DIR/launch_studio.sh
Icon=$VTS_DIR/assets/icon.png
Terminal=false
Categories=AudioVideo;Audio;Video;
StartupNotify=true
EOF
chmod +x "$DESKTOP_FILE"

# ── 8. Configure paths ────────────────────────────────────────────────────────
mkdir -p "$HOME/.config/videotranslator"
if [[ ! -f "$HOME/.config/videotranslator/paths.json" ]]; then
    info "Generujem default paths config"
    VTS_PYTHON="$MINIFORGE_DIR/envs/$VTS_ENV_NAME/bin/python" \
        "$MINIFORGE_DIR/envs/$VTS_ENV_NAME/bin/python" -c \
        "import sys; sys.path.insert(0, '$VTS_DIR'); from scripts.paths import save_paths, load_paths; save_paths(load_paths())"
fi

# ── 9. Hint launcher env ──────────────────────────────────────────────────────
cat > "$VTS_DIR/.env" <<EOF
# Auto-generated by install.sh — override defaults here
VTS_PYTHON=$MINIFORGE_DIR/envs/$VTS_ENV_NAME/bin/python
VTS_CONDA_ROOT=$MINIFORGE_DIR
VTS_PYTHON_ENV=$VTS_ENV_NAME
EOF

info "✓ Inštalácia hotová!"
info ""
info "Spustenie:"
info "  ${GREEN}$VTS_DIR/launch_studio.sh${NC}"
info ""
info "Alebo cez aplikačné menu (hľadaj 'VideoTranslator Studio')."
info ""
info "API kľúče (voliteľné — pre GPT/Grok/Gemini preklad):"
info "  export OPENAI_API_KEY=sk-..."
info "  export GROK_API_KEY=..."
info "  export GEMINI_API_KEY=..."
info "  export HF_API_KEY=...   # pre HuggingFace modely"
